Repository jamadaha/P7, pull requests merged in 2022-12, with the labels that each got.

#330 Subset exploration
  LabSettings/.1s.ini
  LabSettings/.1s_easy.ini
  LabSettings/.1s_hard.ini
  LabSettings/.1s_insane.ini
  LabSettings/.1s_medium.ini
  LabSettings/100s.ini
  LabSettings/100s_easy.ini
  LabSettings/100s_hard.ini
  LabSettings/100s_insane.ini
  LabSettings/100s_medium.ini
  LabSettings/10s.ini
  LabSettings/10s_easy.ini
  LabSettings/10s_hard.ini
  LabSettings/10s_insane.ini
  LabSettings/10s_medium.ini
  LabSettings/1s.ini
  LabSettings/1s_easy.ini
  LabSettings/1s_hard.ini
  LabSettings/1s_insane.ini
  LabSettings/1s_medium.ini
  LabSettings/baseSettings15percent.ini
  LabSettings/baseSettings25percent.ini
  LabSettings/baseSettings50percent.ini
  LabSettings/baseSettings5percent.ini
  LabSettings/depot_sameoutput.ini
  LabSettings/depot_walker_15.ini
  LabSettings/depot_walker_25.ini
  LabSettings/depot_walker_5.ini
  LabSettings/depot_walker_50.ini
  LabSettings/depot_walker_sameoutput.ini
  LabSettings/experiment_1.ini
  LabSettings/experiment_2.ini
  LabSettings/settingsStress_15.ini
  LabSettings/settingsStress_25.ini
  LabSettings/settingsStress_5.ini
  LabSettings/settingsStress_50.ini
  Test/Walker/ActionGenerator.cpp
  baseSettings.ini
  settings.ini
  settingsLab.ini
  src/Walker/ActionGenerator.cpp
  src/Walker/ActionGenerator.hpp
  src/Walker/BaseWalker.hh
  src/Walker/Variants/WalkerGreedy.hpp
  src/Walker/Variants/WalkerGreedyResume.hpp
  src/Walker/Variants/WalkerHillClimber.hpp
  src/Walker/Variants/WalkerProbe.hpp
  src/Walker/Variants/WalkerStepBack.hpp
Labels: feature

#331 new graph
  graphGeneration.R
Labels: feature

#333 Goal Predicate Count improvement
  Test/Walker/Walker.cpp
  settings.ini
  src/PDDL/ActionInstance.cpp
  src/PDDL/ActionInstance.hh
  src/PDDL/CMakeLists.txt
  src/PDDL/Instance.cpp
  src/PDDL/Instance.hh
  src/Regressor/PartialActionGenerator/PartialActionConverter.cpp
  src/Walker/ActionGenerator.cpp
  src/Walker/ActionGenerator2.cpp
  src/Walker/Heuristics/BaseHeuristic.hh
  src/Walker/Heuristics/GoalCountHeuristic.hh
  src/Walker/Heuristics/GoalPredicateCountHeuristic.hh
  src/Walker/Heuristics/PreviousBaseHeuristic.hh
  src/Walker/Heuristics/RandomHeuristic.hh
Labels: feature, optimiZATION

#334 Added the currently used walker heuristic to Lab
  Lab/LabAttributes.py
  Lab/P7LabParser.py
  src/CommonInterface/CommonInterface.cpp
Labels: feature

#339 Added tests for the `GoalPredicateCountHeuristic`
  Test/Walker/CMakeLists.txt
  Test/Walker/Heuristics/GoalPredicateCountHeuristicsTests.cpp
  src/PDDL/State.hh
Labels: test

#341 Added tests for hashes
  .github/workflows/main.yml
  CMakeLists.txt
  CMakePresets.json
  Test/Helpers/CMakeLists.txt
  Test/Helpers/HashesTests.cpp
  Test/JointPaths/HashesTests.cpp
Labels: test

#340 Made tests for the `AlgorithmHelper` class
  Test/Helpers/AlgorithmHelperTests.cpp
  Test/Helpers/CMakeLists.txt
  src/Helpers/AlgorithmHelper.hh
Labels: test

#342 Add exp graph
  graphGeneration.R
Labels: feature

#343 Structure update
  CMakeLists.txt
  README.md
  Structure/Structure.graphml
  Structure/Structure.png
  launchFiles/launch.json
  launchFiles/launch.vs.json
  settingsFast.ini
Labels: refactor, feature

#344 Added so the R script also makes big versions of the graphs
  graphGeneration.R
Labels: feature

#345 Reduced the size of the hash tests
  Test/Helpers/HashesTests.cpp
Labels: bug

#346 Added a base Lab settings
  LabSettings/.1s.ini
  LabSettings/100s.ini
  LabSettings/10s.ini
  LabSettings/1s.ini
  LabSettings/baseLabSettings.ini
Labels: feature

#347 Walker performance graph
  Lab/LabAttributes.py
  Lab/P7LabParser.py
  LabSettings/.1s.ini
  Test/CMakeLists.txt
  Test/Walker/Heuristics/GoalPredicateCountHeuristicsTests.cpp
  graphGeneration.R
  settingsLab.ini
  src/CommonInterface/CommonInterface.cpp
  src/Reformulators/BaseReformulator.hh
  src/Reformulators/Walkers/GreedyResumeWalkerReformulator.cpp
  src/Reformulators/Walkers/GreedyWalkerReformulator.cpp
  src/Reformulators/Walkers/HillClimberWalkerReformulator.cpp
  src/Reformulators/Walkers/ProbeWalkerReformulator.cpp
  src/Reformulators/Walkers/QueueWalkerReformulator.cpp
  src/Reformulators/Walkers/StepBackWalkerReformulator.cpp
  src/Walker/BaseWalker.hh
  src/Walker/Heuristics/BaseHeuristic.hh
  src/Walker/Heuristics/GoalPredicateCountHeuristic.hh
  src/Walker/Variants/WalkerGreedy.cpp
  src/Walker/Variants/WalkerGreedyResume.cpp
  src/Walker/Variants/WalkerHillClimber.cpp
  src/Walker/Variants/WalkerProbe.cpp
  src/Walker/Variants/WalkerQueue.cpp
  src/Walker/Variants/WalkerQueue.hpp
  src/Walker/Variants/WalkerStepBack.cpp
Labels: bug, feature

#360 Added translator operators to lab
  Lab/LabAttributes.py
  settingsLab.ini
Labels: feature

#361 Does negative effects before positive
  src/PDDL/Action.cpp
  src/PDDL/Action.hh
  src/PDDL/State.cpp
  src/PDDL/State.hh
Labels: bug, feature, optimiZATION

#362 New plots
  graphGeneration.R
Labels: feature, R related

#366 Fixed a small typo in the scatter plot graphs
  graphGeneration.R
Labels: bug, R related

#365 Added the `rovers` domain to the Lab files
  LabSettings/problems_all.ini
  LabSettings/problems_easy.ini
Labels: feature

#364 Updated the walker performance graph
  graphGeneration.R
Labels: R related

#363 Updated the macro quality graph
  graphGeneration.R
Labels: R related

#367 Added a new style for the bar graphs
  graphGeneration.R
Labels: R related

#370 More graph updates
  graphGeneration.R
Labels: feature, R related

#376 Removed the unusable rovers domain from the settings files
  LabSettings/problems_all.ini
  LabSettings/problems_easy.ini
Labels: bug

#378 Updated the evaluations graph
  graphGeneration.R
Labels: R related

#379 Fixed graph scaling and cleaned up the R script
  graphGeneration.R
Labels: R related

#380 Search time scatter plot
  graphGeneration.R
Labels: R related

#382 More plot updates!
  graphGeneration.R
Labels: R related

#383 Made the scatter plots in gray scale instead
  graphGeneration.R
Labels: R related

#384 Fix goal count predicate
  LabSettings/baseLabSettings.ini
  Test/CMakeLists.txt
  Test/Walker/CMakeLists.txt
  Test/Walker/Heuristics/GoalPredicateCountHeuristicsTests.cpp
  settingsLab.ini
  src/Walker/Heuristics/BaseHeuristic.hh
  src/Walker/Heuristics/GoalCountHeuristic.hh
  src/Walker/Heuristics/GoalPredicateCountHeuristic.hh
  src/Walker/Heuristics/PreviousBaseHeuristic.hh
  src/Walker/Heuristics/RandomHeuristic.hh
  src/Walker/Variants/WalkerGreedyResume.cpp
  src/Walker/Variants/WalkerHillClimber.cpp
  src/Walker/Variants/WalkerQueue.cpp
Labels: feature
