Repository jamadaha/P7, pull requests merged in 2022-10, with the labels that each got.

#52 Adds time measure
  CMakeLists.txt
  src/CommonInterface/CommonInterface.cpp
  src/CommonInterface/CommonInterface.h
  src/P7.cpp
  src/Report.hh
Labels: feature

#53 Generates time report
  src/P7.cpp
  src/Report.hh
Labels: feature

#56 Adds percent to report print
  src/Report.hh
Labels: feature

#62 Replace domain and problem
  CMakeLists.txt
  src/CommonInterface/CommonInterface.cpp
  src/CommonInterface/CommonInterface.h
  src/Entangler/Entangler.hpp
  src/Entangler/pseudocode
  src/PDDLTypes/PDDLAction.hpp
  src/PDDLTypes/PDDLArg.hpp
  src/PDDLTypes/PDDLDomain.hpp
  src/PDDLTypes/PDDLInstance.hpp
  src/PDDLTypes/PDDLLiteral.hpp
  src/PDDLTypes/PDDLPredicate.hpp
  src/PDDLTypes/PDDLProblem.hpp
  src/PDDLTypes/PDDLType.hpp
  src/Reformulators/BaseReformulator.h
  src/Reformulators/SameOutputReformulator.cpp
  src/Reformulators/SameOutputReformulator.h
Labels: refactor

#64 Makes init state and goal state a specific class
  CMakeLists.txt
  src/PDDLTypes/PDDLProblem.hpp
  src/PDDLTypes/PDDLState.hpp
Labels: refactor

#84 Adds action generation
  CMakeLists.txt
  src/CommonInterface/CommonInterface.cpp
  src/CommonInterface/CommonInterface.h
  src/Entangler/ActionGenerator.cpp
  src/Entangler/ActionGenerator.hpp
  src/Entangler/Entangler.hpp
  src/PDDLTypes/PDDLAction.hpp
  src/PDDLTypes/PDDLActionInstance.hpp
  src/PDDLTypes/PDDLArg.hpp
  src/PDDLTypes/PDDLDomain.hpp
  src/PDDLTypes/PDDLProblem.hpp
  src/PDDLTypes/PDDLState.hpp
Labels: feature

#100 Type fix (Also fixes Walk as a side effect)
  CMakeLists.txt
  README.md
  src/CommonInterface/CommonInterface.cpp
  src/CommonInterface/CommonInterface.hh
  src/Config/config.cpp
  src/Config/config.hh
  src/IntermediatePDDL/PDDLAction.cpp
  src/IntermediatePDDL/PDDLAction.hh
  src/IntermediatePDDL/PDDLArg.hh
  src/IntermediatePDDL/PDDLDomain.cpp
  src/IntermediatePDDL/PDDLProblem.hh
  src/IntermediatePDDL/PDDLState.cpp
  src/IntermediatePDDL/PDDLState.hh
  src/P7.cpp
  src/PDDLCodeGenerator/PDDLProblemCodeGenerator.cpp
  src/Reformulators/RandomWalkerReformulator.cpp
  src/Reformulators/RandomWalkerReformulator.hh
  src/Walker/ActionGenerator.cpp
  src/Walker/ActionGenerator.hpp
  src/Walker/Heuristics/RandomHeuristic.hh
  src/Walker/Walker.cpp
Labels: bug

#104 Walks x times generating paths depending on the heuristic
  src/Reformulators/RandomWalkerReformulator.cpp
  src/Reformulators/RandomWalkerReformulator.hh
  src/Walker/Walker.cpp
  src/Walker/Walker.hpp
Labels: feature

#108 Action generator test (And minor refactor)
  CMakeLists.txt
  Test/CMakeLists.txt
  Test/IntermediatePDDL/IntermediatePDDL.cpp
  Test/PDDLCodeGenerator/PDDLCodeGenerator.cpp
  Test/Walker/ActionGenerator.cpp
  Test/Walker/CMakeLists.txt
  Test/Walker/DepthFunctions/ObjectActionDepthFunction.cpp
  Test/Walker/Walker.cpp
  src/CommonInterface/CommonInterface.cpp
  src/CommonInterface/CommonInterface.hh
  src/IntermediatePDDL/PDDLAction.cpp
  src/IntermediatePDDL/PDDLAction.hh
  src/IntermediatePDDL/PDDLActionInstance.hh
  src/IntermediatePDDL/PDDLArg.hh
  src/IntermediatePDDL/PDDLConverter.cpp
  src/IntermediatePDDL/PDDLConverter.hh
  src/IntermediatePDDL/PDDLDomain.cpp
  src/IntermediatePDDL/PDDLDomain.hh
  src/IntermediatePDDL/PDDLLiteral.hh
  src/IntermediatePDDL/PDDLPredicate.hh
  src/IntermediatePDDL/PDDLProblem.hh
  src/IntermediatePDDL/PDDLState.cpp
  src/IntermediatePDDL/PDDLState.hh
  src/IntermediatePDDL/PDDLType.hh
  src/PDDLCodeGenerator/BasePDDLCodeGenerator.cpp
  src/PDDLCodeGenerator/BasePDDLCodeGenerator.hh
  src/PDDLCodeGenerator/PDDLCodeGenerator.cpp
  src/PDDLCodeGenerator/PDDLCodeGenerator.hh
  src/PDDLCodeGenerator/PDDLDomainCodeGenerator.cpp
  src/PDDLCodeGenerator/PDDLDomainCodeGenerator.hh
  src/PDDLCodeGenerator/PDDLProblemCodeGenerator.cpp
  src/PDDLCodeGenerator/PDDLProblemCodeGenerator.hh
  src/Reformulators/RandomWalkerReformulator.cpp
  src/Walker/ActionGenerator.cpp
  src/Walker/ActionGenerator.hpp
  src/Walker/Walker.cpp
  src/Walker/Walker.hpp
Labels: test, refactor

#111 Adds handling of doing an action
  src/IntermediatePDDL/PDDLState.hh
  src/Reformulators/RandomWalkerReformulator.cpp
  src/Walker/ActionGenerator.cpp
  src/Walker/Walker.cpp
  src/Walker/Walker.hpp
Labels: feature

#119 Optimize maybe
  src/IntermediatePDDL/PDDLState.hh
  src/Reformulators/RandomWalkerReformulator.cpp
  src/Reformulators/RandomWalkerReformulator.hh
  src/Walker/ActionGenerator.cpp
  src/Walker/ActionGenerator.hpp
  src/Walker/Walker.cpp
  src/Walker/Walker.hpp
  src/Walker/WidthFunctions/ConstantWidthFunction.hh
Labels: refactor

#124 Minor optimization
  src/Reformulators/RandomWalkerReformulator.cpp
  src/Walker/ActionGenerator.cpp
Labels: optimiZATION

#131 Fixes Cmake
  CMakeLists.txt
  README.md
  Test/CMakeLists.txt
  Test/DownwardRunner/CMakeLists.txt
  Test/DownwardRunner/DownwardRunner.cpp
  Test/Helpers/CMakeLists.txt
  Test/IntermediatePDDL/CMakeLists.txt
  Test/PDDLCodeGenerator/CMakeLists.txt
  Test/PDDLParser/CMakeLists.txt
  Test/PlanValidators/CMakeLists.txt
  Test/SASCodeGenerator/CMakeLists.txt
  Test/SASParser/CMakeLists.txt
  Test/Walker/CMakeLists.txt
  Test/Walker/DepthFunctions/CMakeLists.txt
  installScript
  runP7.py
  src/CMakeLists.txt
  src/CommonInterface/CMakeLists.txt
  src/CommonInterface/CommonInterface.hh
  src/Config/CMakeLists.txt
  src/Config/Config.cpp
  src/Config/Config.hh
  src/DownwardRunner/CMakeLists.txt
  src/DownwardRunner/DownwardRunner.hh
  src/FileVerifier/CMakeLists.txt
  src/Helpers/CMakeLists.txt
  src/IntermediatePDDL/CMakeLists.txt
  src/P7.cpp
  src/P7.hh
  src/PDDLCodeGenerator/CMakeLists.txt
  src/PDDLParser/CMakeLists.txt
  src/PathCheckers/CMakeLists.txt
  src/PathCheckers/PathChecker.hh
  src/PlanValidators/CMakeLists.txt
  src/PlanValidators/PlanValidator.hh
  src/Reformulators/BaseReformulator.hh
  src/Reformulators/CMakeLists.txt
  src/Reformulators/RandomWalkerReformulator.hh
  src/Reformulators/SameOutputReformulator.hh
  src/RunReport/CMakeLists.txt
  src/SASCodeGenerator/CMakeLists.txt
  src/SASParser/CMakeLists.txt
  src/Walker/CMakeLists.txt
  src/Walker/DepthFunctions/CMakeLists.txt
  src/Walker/WidthFunctions/CMakeLists.txt
Labels: refactor

#135 Fixes a bug in DoAction
  Test/CMakeLists.txt
  Test/Walker/ActionGenerator.cpp
  Test/Walker/CMakeLists.txt
  Test/Walker/DepthFunctions/CMakeLists.txt
  Test/Walker/Walker.cpp
  src/IntermediatePDDL/CMakeLists.txt
  src/IntermediatePDDL/PDDLAction.cpp
  src/IntermediatePDDL/PDDLAction.hh
  src/IntermediatePDDL/PDDLState.hh
  src/Reformulators/RandomWalkerReformulator.cpp
  src/Walker/ActionGenerator.cpp
  src/Walker/ActionGenerator.hpp
  src/Walker/Walker.cpp
  src/Walker/Walker.hpp
Labels: bug, test, refactor

#138 Hash actioninstance
  src/IntermediatePDDL/PDDLAction.hh
  src/IntermediatePDDL/PDDLActionInstance.hh
  src/IntermediatePDDL/PDDLLiteral.hh
Labels: feature

#143 Actiongenerator test
  Test/Walker/ActionGenerator.cpp
  src/IntermediatePDDL/PDDLActionInstance.hh
  src/IntermediatePDDL/PDDLPredicate.hh
  src/IntermediatePDDL/PDDLState.hh
  src/Reformulators/RandomWalkerReformulator.cpp
  src/Walker/ActionGenerator.cpp
  src/Walker/ActionGenerator.hpp
  src/Walker/Walker.cpp
Labels: test

#147 Adds applicable predicates
  src/IntermediatePDDL/PDDLAction.cpp
  src/IntermediatePDDL/PDDLAction.hh
Labels: optimiZATION

#152 Breaks on revisit
  settings.ini
  src/EntanglementFinder/CMakeLists.txt
  src/EntanglementFinder/EntanglementFinder.cpp
  src/EntanglementFinder/EntanglementOccurance.cpp
  src/EntanglementFinder/EntanglementOccurance.hh
  src/IntermediatePDDL/PDDLActionInstance.hh
  src/IntermediatePDDL/PDDLState.hh
  src/Reformulators/RandomWalkerReformulator.cpp
  src/Walker/Walker.cpp
Labels: feature

#156 Added a Progressbar
  Test/EntanglementFinder/CMakeLists.txt
  installScript
  settings.ini
  settingsFast.ini
  src/CMakeLists.txt
  src/EntanglementFinder/CMakeLists.txt
  src/EntanglementFinder/EntanglementFinder.cpp
  src/EntanglementFinder/EntanglementFinder.hh
  src/Helpers/CMakeLists.txt
  src/Helpers/ConsoleHelper.cpp
  src/Helpers/ConsoleHelper.hh
  src/Helpers/ProgressBarHelper.cpp
  src/Helpers/ProgressBarHelper.hh
  src/Reformulators/RandomWalkerReformulator.cpp
  src/Reformulators/RandomWalkerReformulator.hh
Labels: feature

#158 Goal Count Heuristic
  CMakeLists.txt
  Test/CMakeLists.txt
  Test/Walker/Walker.cpp
  settings.ini
  settingsFast.ini
  src/CMakeLists.txt
  src/CommonInterface/CommonInterface.cpp
  src/CommonInterface/CommonInterface.hh
  src/Helpers/CMakeLists.txt
  src/Helpers/Hashes.cpp
  src/Helpers/Hashes.hh
  src/IntermediatePDDL/PDDLActionInstance.hh
  src/IntermediatePDDL/PDDLState.cpp
  src/IntermediatePDDL/PDDLState.hh
  src/Reformulators/CMakeLists.txt
  src/Reformulators/WalkerReformulator.cpp
  src/Reformulators/WalkerReformulator.hh
  src/Walker/ActionGenerator.cpp
  src/Walker/ActionGenerator.hpp
  src/Walker/CMakeLists.txt
  src/Walker/Heuristics/BaseHeuristic.hh
  src/Walker/Heuristics/BaseHeuristics.hh
  src/Walker/Heuristics/Contexts/BaseContext.hh
  src/Walker/Heuristics/Contexts/PDDLContext.hh
  src/Walker/Heuristics/GoalCountHeuristic.hh
  src/Walker/Heuristics/RandomHeuristic.hh
  src/Walker/Walker.cpp
  src/Walker/Walker.hpp
  src/Walker/WidthFunctions/BaseWidthFunction.hh
  src/Walker/WidthFunctions/CMakeLists.txt
  src/Walker/WidthFunctions/ConstantWidthFunction.cpp
  src/Walker/WidthFunctions/ConstantWidthFunction.hh
  src/Walker/WidthFunctions/TimeWidthFunction.cpp
  src/Walker/WidthFunctions/TimeWidthFunction.hh
Labels: refactor, feature

#160 Better Entangler Finder progress bars
  Test/EntanglementFinder/EntanglementFinder.cpp
  settings.ini
  src/EntanglementFinder/CMakeLists.txt
  src/EntanglementFinder/EntanglementFinder.cpp
  src/EntanglementFinder/EntanglementFinder.hh
  src/EntanglementFinder/EntanglementOccurance.cpp
  src/EntanglementFinder/EntanglementOccurance.hh
  src/IntermediatePDDL/PDDLActionInstance.hh
  src/Reformulators/WalkerReformulator.cpp
  src/Reformulators/WalkerReformulator.hh
  src/Walker/Walker.cpp
  src/Walker/Walker.hpp
Labels: refactor, feature, optimiZATION

#163 Added a time limit option for the entanglement finder
  settings.ini
  settingsFast.ini
  src/EntanglementFinder/EntanglementFinder.cpp
  src/EntanglementFinder/EntanglementFinder.hh
  src/Reformulators/WalkerReformulator.cpp
Labels: feature

#164 adds copy on change
  CMakeLists.txt
Labels: feature

#165 Entanglement evaluator
  Test/EntanglementFinder/EntanglementFinder.cpp
  settings.ini
  settingsFast.ini
  src/EntanglementFinder/CMakeLists.txt
  src/EntanglementFinder/EntanglementEvaluator.cpp
  src/EntanglementFinder/EntanglementEvaluator.hh
  src/EntanglementFinder/EntanglementEvaluatorModifiers.hh
  src/EntanglementFinder/EntanglementFinder.cpp
  src/EntanglementFinder/EntanglementFinder.hh
  src/EntanglementFinder/EntanglementOccurance.hh
  src/Reformulators/WalkerReformulator.cpp
  src/Reformulators/WalkerReformulator.hh
Labels: feature

#167 Fix duplicate state in goal count
  src/IntermediatePDDL/PDDLState.hh
  src/Walker/Walker.cpp
Labels: feature

#169 Added so that the minimum occurance is a percentage instead
  settings.ini
  settingsFast.ini
  src/Config/Config.cpp
  src/Config/Config.hh
  src/EntanglementFinder/EntanglementEvaluator.cpp
  src/EntanglementFinder/EntanglementEvaluator.hh
  src/Reformulators/WalkerReformulator.cpp
Labels: feature

#171 Added a subtraction reduction type ot the entanglement finder
  settings.ini
  settingsFast.ini
  src/EntanglementFinder/EntanglementFinder.cpp
  src/EntanglementFinder/EntanglementFinder.hh
  src/Reformulators/WalkerReformulator.cpp
Labels: feature

#172 New heuristic
  Data/Classical tracks/Gripper/gripper_problem_hard.pddl
  settings.ini
  settingsFast.ini
  src/Reformulators/WalkerReformulator.cpp
  src/Reformulators/WalkerReformulator.hh
  src/Walker/Heuristics/GoalPredicateCountHeuristic.hh
Labels: feature

#180 Grounded macro generation
  CMakeLists.txt
  settings.ini
  settingsFast.ini
  src/CMakeLists.txt
  src/CommonInterface/CommonInterface.cpp
  src/DownwardRunner/DownwardRunner.cpp
  src/IntermediatePDDL/PDDLLiteral.hh
  src/IntermediatePDDL/PDDLPredicate.hh
  src/MacroGenerator/CMakeLists.txt
  src/MacroGenerator/GroundedAction.hh
  src/MacroGenerator/InstanceGenerator.cpp
  src/MacroGenerator/InstanceGenerator.hh
  src/MacroGenerator/Macro.hh
  src/MacroGenerator/MacroGenerator.cpp
  src/MacroGenerator/MacroGenerator.hh
  src/Reformulators/BaseReformulator.hh
  src/Reformulators/CMakeLists.txt
  src/Reformulators/SameOutputReformulator.cpp
  src/Reformulators/SameOutputReformulator.hh
  src/Reformulators/WalkerReformulator.cpp
  src/Reformulators/WalkerReformulator.hh
Labels: feature

#185 Change multifacts to set
  Test/Walker/ActionGenerator.cpp
  Test/Walker/Walker.cpp
  src/IntermediatePDDL/PDDLConverter.cpp
  src/IntermediatePDDL/PDDLConverter.hh
  src/IntermediatePDDL/PDDLState.cpp
  src/IntermediatePDDL/PDDLState.hh
  src/MacroGenerator/InstanceGenerator.cpp
Labels: refactor, optimiZATION

#186 Small optimization
  src/IntermediatePDDL/PDDLState.hh
  src/Walker/Heuristics/GoalPredicateCountHeuristic.hh
Labels: optimiZATION

#189 Add walker information to report
  src/CommonInterface/CommonInterface.cpp
  src/Reformulators/BaseReformulator.hh
  src/Reformulators/SameOutputReformulator.hh
  src/Reformulators/WalkerReformulator.cpp
  src/Reformulators/WalkerReformulator.hh
  src/RunReport/RunReport.cpp
  src/RunReport/RunReport.hh
  src/Walker/ActionGenerator.hpp
  src/Walker/Walker.cpp
  src/Walker/Walker.hpp
Labels: feature

#190 Add macro name
  src/MacroGenerator/MacroGenerator.cpp
Labels: feature
