Repository jamadaha/P7, pull requests merged in 2022-11, with the labels that each got.

#195 Hash functions tests
  Test/CMakeLists.txt
  Test/EntanglementFinder/CMakeLists.txt
  Test/EntanglementFinder/EntanglementFinder.cpp
  Test/EntanglementFinder/Hashes.cpp
  src/Helpers/Hashes.hh
  src/IntermediatePDDL/PDDLAction.hh
  src/IntermediatePDDL/PDDLActionInstance.hh
Labels: test

#201 Fixed configs
  settings.ini
  settingsFast.ini
  settingsLab.ini
  settingsLabMultiple.ini
  settingsStress.ini
Labels: bug

#203 Improvements to the `EntanglementEvaluator`
  settings.ini
  settingsFast.ini
  settingsLab.ini
  settingsLabMultiple.ini
  settingsStress.ini
  src/EntanglementFinder/EntanglementEvaluator.cpp
  src/EntanglementFinder/EntanglementEvaluator.hh
  src/EntanglementFinder/EntanglementEvaluatorModifiers.hh
  src/Reformulators/WalkerReformulator.cpp
Labels: feature, optimiZATION

#204 Iterative Execution of Walker/Downward
  settings.ini
  settingsFast.ini
  settingsLab.ini
  settingsLabMultiple.ini
  settingsStress.ini
  src/CommonInterface/CommonInterface.cpp
  src/CommonInterface/CommonInterface.hh
  src/DownwardRunner/DownwardRunner.cpp
  src/DownwardRunner/DownwardRunner.hh
  src/EntanglementFinder/EntanglementFinder.cpp
  src/EntanglementFinder/EntanglementFinder.hh
  src/Helpers/ProgressBarHelper.hh
  src/P7.cpp
  src/Reformulators/BaseReformulator.hh
  src/Reformulators/SameOutputReformulator.cpp
  src/Reformulators/SameOutputReformulator.hh
  src/Reformulators/WalkerReformulator.cpp
  src/Reformulators/WalkerReformulator.hh
  src/RunReport/RunReport.cpp
  src/RunReport/RunReport.hh
  src/Walker/Walker.cpp
  src/Walker/Walker.hpp
Labels: feature, optimiZATION

#206 Macro tests
  Test/CMakeLists.txt
  Test/MacroGenerator/CMakeLists.txt
  Test/MacroGenerator/MacroGenerator.cpp
  src/MacroGenerator/MacroGenerator.hh
Labels: test

#205 Binary facts
  Test/Walker/ActionGenerator.cpp
  Test/Walker/Walker.cpp
  src/Helpers/Hashes.hh
  src/IntermediatePDDL/PDDLConverter.cpp
  src/IntermediatePDDL/PDDLConverter.hh
  src/IntermediatePDDL/PDDLState.hh
  src/MacroGenerator/InstanceGenerator.cpp
  src/PDDLCodeGenerator/PDDLProblemCodeGenerator.cpp
  src/Walker/ActionGenerator.cpp
  src/Walker/ActionGenerator.hpp
  src/Walker/Walker.cpp
Labels: optimiZATION

#209 Makes pipeline case insensitive
  Test/IntermediatePDDL/CMakeLists.txt
  Test/IntermediatePDDL/IntermediatePDDL.cpp
  Test/PDDLCodeGenerator/CMakeLists.txt
  src/IntermediatePDDL/PDDLConverter.cpp
  src/IntermediatePDDL/PDDLConverter.hh
Labels: bug, feature

#208 Fixes
  settings.ini
  settingsFast.ini
  settingsLab.ini
  settingsLabMultiple.ini
  settingsStress.ini
  src/CommonInterface/CommonInterface.cpp
  src/DownwardRunner/DownwardRunner.cpp
  src/EntanglementFinder/EntanglementEvaluator.cpp
  src/EntanglementFinder/EntanglementEvaluator.hh
  src/PDDLCodeGenerator/PDDLDomainCodeGenerator.cpp
  src/Reformulators/WalkerReformulator.cpp
Labels: bug, feature

#214 Makes sure to reset macros for each iteration
  src/Reformulators/WalkerReformulator.cpp
  src/Reformulators/WalkerReformulator.hh
Labels: bug

#215 Config overwrites
  CMakeLists.txt
  baseSettings.ini
  runP7.py
  settings.ini
  settingsFast.ini
  settingsLab.ini
  settingsLabMultiple.ini
  settingsStress.ini
  src/Config/Config.cpp
  src/Config/Config.hh
Labels: feature

#219 Added an option to split the time between the reformulator and downward runner
  baseSettings.ini
  src/CommonInterface/CommonInterface.cpp
  src/CommonInterface/CommonInterface.hh
  src/DownwardRunner/DownwardRunner.cpp
  src/Reformulators/WalkerReformulator.cpp
Labels: feature

#218 Fix binary facts
  Test/Walker/ActionGenerator.cpp
  Test/Walker/Walker.cpp
  src/Helpers/AlgorithmHelper.cpp
  src/Helpers/AlgorithmHelper.hh
  src/Helpers/CMakeLists.txt
  src/IntermediatePDDL/PDDLState.cpp
  src/IntermediatePDDL/PDDLState.hh
  src/Reformulators/WalkerReformulator.cpp
  src/Walker/ActionGenerator.cpp
  src/Walker/ActionGenerator.hpp
  src/Walker/CMakeLists.txt
  src/Walker/Pseudocode
  src/Walker/pseudocode
Labels: bug

#223 Remove unneeded macro preconditions
  src/IntermediatePDDL/PDDLDomain.hh
  src/MacroGenerator/MacroGenerator.cpp
  src/MacroGenerator/MacroGenerator.hh
Labels: feature

#229 Adds an option to run a reformulator in "direct" mode instead of iteratively
  baseSettings.ini
  settings.ini
  settingsFast.ini
  src/CommonInterface/CommonInterface.cpp
  src/CommonInterface/CommonInterface.hh
  src/Config/Config.cpp
  src/P7.cpp
  src/Reformulators/WalkerReformulator.cpp
Labels: feature

#232 Set the validation of plans to be a flag for itself
  baseSettings.ini
  src/CommonInterface/CommonInterface.cpp
Labels: feature

#237 Lab Improvements
  Lab/P7LabParser.py
  Lab/Reports.py
  Lab/SingleSearchParser.py
  runP7.py
  settingsStress.ini
  src/CommonInterface/CommonInterface.cpp
  src/CommonInterface/CommonInterface.hh
  src/P7.cpp
  src/RunReport/RunReport.cpp
  src/RunReport/RunReport.hh
Labels: feature

#231 Refactor search algorithms
  CMakeLists.txt
  Test/CMakeLists.txt
  Test/Walker/DepthFunctions/CMakeLists.txt
  Test/Walker/DepthFunctions/ConstantDepthFunction.cpp
  Test/Walker/DepthFunctions/ObjectActionDepthFunction.cpp
  src/CMakeLists.txt
  src/Reformulators/WalkerReformulator.cpp
  src/Reformulators/WalkerReformulator.hh
  src/Walker/BaseWalker.hh
  src/Walker/CMakeLists.txt
  src/Walker/DepthFunctions/CMakeLists.txt
  src/Walker/DepthFunctions/ConstantDepthFunction.cpp
  src/Walker/DepthFunctions/ConstantDepthFunction.hh
  src/Walker/DepthFunctions/ObjectActionDepthFunction.cpp
  src/Walker/DepthFunctions/ObjectActionDepthFunction.hh
  src/Walker/Heuristics/CMakeLists.txt
  src/Walker/Heuristics/GreedyHeuristic.cpp
  src/Walker/Heuristics/GreedyHeuristic.hh
  src/Walker/Heuristics/RandomHeuristic.hh
  src/Walker/Walker.cpp
  src/Walker/Walker.hpp
  src/Walker/WalkerBuilder.cpp
  src/Walker/WalkerBuilder.hpp
Labels: feature

#240 Bfr
  Test/EntanglementFinder/EntanglementFinder.cpp
  Test/EntanglementFinder/Hashes.cpp
  Test/Walker/Walker.cpp
  baseSettings.ini
  src/EntanglementFinder/EntanglementEvaluator.hh
  src/EntanglementFinder/EntanglementFinder.hh
  src/IntermediatePDDL/PDDLConverter.cpp
  src/IntermediatePDDL/PDDLState.hh
  src/Walker/BaseWalker.hh
  src/Walker/CMakeLists.txt
  src/Walker/Heuristics/GoalCountHeuristic.hh
  src/Walker/Heuristics/GoalPredicateCountHeuristic.hh
  src/Walker/Path.hpp
  src/Walker/Variants/Walker.cpp
  src/Walker/Variants/Walker.hpp
  src/Walker/Variants/WalkerQueue.cpp
  src/Walker/Variants/WalkerQueue.hpp
  src/Walker/Variants/WalkerResume.cpp
  src/Walker/Variants/WalkerResume.hpp
  src/Walker/WalkerBuilder.cpp
  src/Walker/WalkerBuilder.hpp
Labels: feature

#241 Added translator facts and real plan lengths to the report
  Lab/Reports.py
  src/CommonInterface/CommonInterface.cpp
Labels: feature

#246 Move walker variants to reformulators
  LabSettings/depot_walker_15.ini
  LabSettings/depot_walker_25.ini
  LabSettings/depot_walker_5.ini
  LabSettings/depot_walker_50.ini
  LabSettings/settingsStress_15.ini
  LabSettings/settingsStress_25.ini
  LabSettings/settingsStress_5.ini
  LabSettings/settingsStress_50.ini
  baseSettings.ini
  settings.ini
  settingsFast.ini
  src/CommonInterface/CommonInterface.cpp
  src/CommonInterface/CommonInterface.hh
  src/MacroGenerator/MacroGenerator.cpp
  src/MacroGenerator/MacroGenerator.hh
  src/Reformulators/BaseReformulator.hh
  src/Reformulators/CMakeLists.txt
  src/Reformulators/WalkerReformulator.cpp
  src/Reformulators/WalkerReformulator.hh
  src/Reformulators/Walkers/BaseWalkerReformulator.cpp
  src/Reformulators/Walkers/BaseWalkerReformulator.hh
  src/Reformulators/Walkers/GreedyResumeWalkerReformulator.cpp
  src/Reformulators/Walkers/GreedyResumeWalkerReformulator.hh
  src/Reformulators/Walkers/GreedyWalkerReformulator.cpp
  src/Reformulators/Walkers/GreedyWalkerReformulator.hh
  src/Reformulators/Walkers/QueueWalkerReformulator.cpp
  src/Reformulators/Walkers/QueueWalkerReformulator.hh
  src/Walker/CMakeLists.txt
  src/Walker/Variants/WalkerGreedy.cpp
  src/Walker/Variants/WalkerGreedy.hpp
  src/Walker/Variants/WalkerGreedyResume.cpp
  src/Walker/Variants/WalkerGreedyResume.hpp
  src/Walker/WalkerBuilder.cpp
  src/Walker/WalkerBuilder.hpp
Labels: refactor

#254 Entangler runtime fix
  baseSettings.ini
  src/EntanglementFinder/EntanglementFinder.cpp
  src/EntanglementFinder/EntanglementFinder.hh
  src/Reformulators/Walkers/BaseWalkerReformulator.cpp
  src/Reformulators/Walkers/GreedyResumeWalkerReformulator.cpp
  src/Reformulators/Walkers/GreedyWalkerReformulator.cpp
  src/Reformulators/Walkers/QueueWalkerReformulator.cpp
Labels: bug

#255 New Downward options
  Lab/Reports.py
  LabSettings/depot_walker_sameoutput.ini
  baseSettings.ini
  runP7.py
  src/DownwardRunner/DownwardRunner.cpp
Labels: feature

#253 Probe walker
  LabSettings/depot_walker_sameoutput.ini
  baseSettings.ini
  settings.ini
  src/CommonInterface/CommonInterface.cpp
  src/CommonInterface/CommonInterface.hh
  src/DownwardRunner/DownwardRunner.cpp
  src/Reformulators/CMakeLists.txt
  src/Reformulators/Walkers/ProbeWalkerReformulator.cpp
  src/Reformulators/Walkers/ProbeWalkerReformulator.hh
  src/Walker/CMakeLists.txt
  src/Walker/Variants/WalkerProbe.cpp
  src/Walker/Variants/WalkerProbe.hpp
  src/Walker/WalkerBuilder.cpp
  src/Walker/WalkerBuilder.hpp
Labels: feature

#256 Lab additions
  CMakeLists.txt
  Lab/Benchmarks.py
  Lab/CSVGenerator.py
  Lab/ConfigParser.py
  Lab/LabAttributes.py
  Lab/LabSettingsParser.py
  Lab/LabSuite.py
  Lab/PathHelper.py
  Lab/Reports.py
  Lab/RunReplacement.py
  Lab/SettingsParser.py
  LabSettings/depot_walker_sameoutput.ini
  runP7.py
  settingsLab.ini
Labels: refactor, feature

#263 More Lab work
  Lab/LabAttributes.py
  Lab/LabSettingsParser.py
  Lab/LabSuite.py
  Lab/P7LabParser.py
  Lab/Reports.py
  Lab/SingleSearchParser.py
  LabSettings/depot_walker_sameoutput.ini
  settingsLab.ini
  src/CommonInterface/CommonInterface.cpp
  src/Reformulators/SameOutputReformulator.cpp
  src/Reformulators/Walkers/BaseWalkerReformulator.cpp
  src/RunReport/RunReport.cpp
  src/RunReport/RunReport.hh
  src/SASParser/SASParser.cpp
  src/SASParser/SASParser.hh
Labels: feature

#270 Lab rounds and macro count
  Lab/LabAttributes.py
  Lab/LabSettingsParser.py
  Lab/LabSuite.py
  Lab/P7LabParser.py
  LabSettings/depot_walker_sameoutput.ini
  settingsLab.ini
  src/CommonInterface/CommonInterface.cpp
  src/Reformulators/BaseReformulator.hh
  src/Reformulators/Walkers/BaseWalkerReformulator.cpp
Labels: feature

#274 Macro verification
  CMakeLists.txt
  Lab/AnytimeSearchParser.py
  Lab/P7LabParser.py
  Lab/PlannerParser.py
  Lab/SingleSearchParser.py
  Lab/TranslatorParser.py
  baseSettings.ini
  settings.ini
  settingsFast.ini
  src/CMakeLists.txt
  src/CommonInterface/CommonInterface.cpp
  src/CommonInterface/CommonInterface.hh
  src/MacroVerifyer/CMakeLists.txt
  src/MacroVerifyer/MacroVerifyer.cpp
  src/MacroVerifyer/MacroVerifyer.hh
  src/Reformulators/BaseReformulator.hh
  src/Reformulators/Walkers/BaseWalkerReformulator.cpp
  src/Reformulators/Walkers/BaseWalkerReformulator.hh
Labels: bug, feature

#279 Bonked multifacts
  Test/PDDLCodeGenerator/PDDLCodeGenerator.cpp
  Test/Walker/ActionGenerator.cpp
  Test/Walker/Walker.cpp
  src/IntermediatePDDL/PDDLConverter.cpp
  src/IntermediatePDDL/PDDLConverter.hh
  src/IntermediatePDDL/PDDLState.cpp
  src/IntermediatePDDL/PDDLState.hh
  src/MacroGenerator/InstanceGenerator.cpp
  src/PDDLCodeGenerator/PDDLProblemCodeGenerator.cpp
  src/Walker/ActionGenerator.cpp
  src/Walker/Heuristics/GoalCountHeuristic.hh
  src/Walker/Heuristics/GoalPredicateCountHeuristic.hh
  src/Walker/Variants/WalkerGreedy.cpp
  src/Walker/Variants/WalkerGreedyResume.cpp
  src/Walker/Variants/WalkerProbe.cpp
Labels: refactor

#278 Added total progress to Lab
  Lab/LabSuite.py
  Lab/RunReplacement.py
Labels: feature

#280 Fixed a bug
  src/CommonInterface/CommonInterface.cpp
Labels: bug

#281 Graph generation
  CMakeLists.txt
  LabSettings/experiment_1.ini
  LabSettings/experiment_2.ini
  LabSettings/problems_all.ini
  LabSettings/problems_easy.ini
  LabSettings/problems_easy_timetest.ini
  LabSettings/problems_hard.ini
  LabSettings/problems_hard_timetest.ini
  LabSettings/problems_insane.ini
  LabSettings/problems_insane_timetest.ini
  LabSettings/problems_medium.ini
  LabSettings/problems_medium_timetest.ini
  baseSettings.ini
  graphGeneration
  installScript.sh
  settingsLab.ini
  src/Walker/Variants/WalkerQueue.cpp
  src/Walker/Variants/WalkerQueue.hpp
Labels: feature

#282 Lab and R
  CMakeLists.txt
  Lab/LabSettingsParser.py
  Lab/LabSuite.py
  Lab/Reports.py
  Lab/__init__.py
  graphGeneration.R
  runP7.py
  settingsLab.ini
Labels: feature

#283 New graphs
  graphGeneration.R
Labels: feature

#284 Also print binary facts
  src/IntermediatePDDL/PDDLState.cpp
  src/Walker/Heuristics/BaseHeuristic.hh
  src/Walker/Heuristics/GreedyHeuristic.hh
  src/Walker/Heuristics/RandomHeuristic.hh
  src/Walker/WalkerBuilder.cpp
  src/Walker/WalkerBuilder.hpp
Labels: feature

#285 Fixed run modes
  Lab/LabSuite.py
  Lab/SettingsParser.py
  LabSettings/depot_walker_sameoutput.ini
Labels: bug

#286 Made VAL's output verbose
  src/PlanValidators/PlanValidator.cpp
Labels: feature

#287 Fixes permuteall not being able to handle decreasing order in precondition
  src/Reformulators/Walkers/BaseWalkerReformulator.cpp
  src/Walker/ActionGenerator.cpp
  src/Walker/Path.cpp
  src/Walker/Path.hh
Labels: bug

#289 Various Fixes
  LabSettings/experiment_1.ini
  src/MacroVerifyer/MacroVerifyer.cpp
  src/Reformulators/Walkers/BaseWalkerReformulator.cpp
  src/Walker/Variants/WalkerGreedyResume.cpp
  src/Walker/Variants/WalkerGreedyResume.hpp
  src/Walker/Variants/WalkerQueue.cpp
  src/Walker/Variants/WalkerQueue.hpp
Labels: bug

#290 Fixes undoaction ... I think
  src/Helpers/Hashes.hh
  src/IntermediatePDDL/PDDLState.cpp
  src/IntermediatePDDL/PDDLState.hh
  src/Walker/Heuristics/GoalCountHeuristic.hh
  src/Walker/Heuristics/GoalPredicateCountHeuristic.hh
  src/Walker/Variants/WalkerQueue.cpp
Labels: bug

#292 Potential new action generator
  LabSettings/depot_walker_sameoutput.ini
  baseSettings.ini
  settings.ini
  src/IntermediatePDDL/PDDLAction.hh
  src/IntermediatePDDL/PDDLActionInstance.hh
  src/IntermediatePDDL/PDDLConverter.cpp
  src/Walker/ActionGenerator2.cpp
  src/Walker/ActionGenerator2.hpp
  src/Walker/BaseWalker.hh
  src/Walker/CMakeLists.txt
  src/Walker/Variants/WalkerQueue.cpp
  src/WalkerPathVerifyer/WalkerPathVerifyer.cpp
Labels: feature

#315 Regression
  CMakeLists.txt
  baseSettings.ini
  installScript.sh
  settings.ini
  src/CMakeLists.txt
  src/CommonInterface/CommonInterface.cpp
  src/CommonInterface/CommonInterface.hh
  src/DownwardRunner/CMakeLists.txt
  src/DownwardRunner/DownwardRunner.cpp
  src/DownwardRunner/DownwardRunner.hh
  src/DownwardRunner/H2Runner.cpp
  src/DownwardRunner/H2Runner.hh
  src/Helpers/AlgorithmHelper.hh
  src/IntermediatePDDL/CMakeLists.txt
  src/IntermediatePDDL/PDDLAction.cpp
  src/IntermediatePDDL/PDDLAction.hh
  src/IntermediatePDDL/PDDLConverter.cpp
  src/IntermediatePDDL/PDDLDomain.hh
  src/IntermediatePDDL/PDDLInstance.hh
  src/IntermediatePDDL/PDDLMutex.hh
  src/Reformulators/BaseReformulator.cpp
  src/Reformulators/BaseReformulator.hh
  src/Reformulators/CMakeLists.txt
  src/Reformulators/Regressors/BaseRegressorReformulator.cpp
  src/Reformulators/Regressors/BaseRegressorReformulator.hh
  src/Reformulators/Regressors/PartialRegressionReformulator.cpp
  src/Reformulators/Regressors/PartialRegressionReformulator.hh
  src/Reformulators/Regressors/RegressionReformulator.cpp
  src/Reformulators/Regressors/RegressionReformulator.hh
  src/Reformulators/Walkers/BaseWalkerReformulator.cpp
  src/Reformulators/Walkers/BaseWalkerReformulator.hh
  src/Regressor/BaseRegressor.cpp
  src/Regressor/BaseRegressor.hh
  src/Regressor/CMakeLists.txt
  src/Regressor/PartialActionGenerator/CMakeLists.txt
  src/Regressor/PartialActionGenerator/PartialAction.hh
  src/Regressor/PartialActionGenerator/PartialActionConverter.cpp
  src/Regressor/PartialActionGenerator/PartialActionConverter.hh
  src/Regressor/PartialActionGenerator/PartialActionGenerator.cpp
  src/Regressor/PartialActionGenerator/PartialActionGenerator.hh
  src/Regressor/PartialRegressor.cpp
  src/Regressor/PartialRegressor.hh
  src/Regressor/Regression.png
  src/Regressor/Regressor.cpp
  src/Regressor/Regressor.hh
  src/Regressor/unnamed0.png
  src/Walker/BaseWalker.hh
Labels: feature

#307 Removed the unused "FileVerifier"
  CMakeLists.txt
  Test/CMakeLists.txt
  src/CMakeLists.txt
  src/FileVerifier/CMakeLists.txt
  src/FileVerifier/FileVerifier.cpp
  src/FileVerifier/FileVerifier.hh
Labels: refactor

#310 Entanglement evaluator (JointPaths Evaluator) tests
  CMakeLists.txt
  Test/CMakeLists.txt
  Test/EntanglementFinder/CMakeLists.txt
  Test/JointPaths/CMakeLists.txt
  Test/JointPaths/EvaluatorTests.cpp
  Test/JointPaths/FinderTests.cpp
  Test/JointPaths/HashesTests.cpp
  settings.ini
  src/CMakeLists.txt
  src/EntanglementFinder/CMakeLists.txt
  src/EntanglementFinder/EntanglementEvaluator.cpp
  src/EntanglementFinder/EntanglementEvaluator.hh
  src/EntanglementFinder/EntanglementEvaluatorModifiers.hh
  src/EntanglementFinder/EntanglementFinder.hh
  src/EntanglementFinder/EntanglementOccurance.hh
  src/JointPaths/CMakeLists.txt
  src/JointPaths/Evaluator/EvaluationModifiers.hh
  src/JointPaths/Evaluator/Evaluator.cpp
  src/JointPaths/Evaluator/Evaluator.hh
  src/JointPaths/Finder/Finder.cpp
  src/JointPaths/Finder/Finder.hh
  src/JointPaths/JointPath.cpp
  src/JointPaths/JointPath.hh
  src/Reformulators/BaseReformulator.cpp
  src/Reformulators/BaseReformulator.hh
  src/Reformulators/Regressors/BaseRegressorReformulator.cpp
  src/Reformulators/Walkers/BaseWalkerReformulator.cpp
Labels: bug, test, refactor

#306 Refactoring of the entire SAS structure
  .gitignore
  CMakeLists.txt
  Test/CMakeLists.txt
  Test/PDDLCodeGenerator/PDDLCodeGenerator.cpp
  Test/SAS/CMakeLists.txt
  Test/SAS/CodeGenerator/CodeGeneratorTests.cpp
  Test/SAS/CodeGenerator/TestFiles/sas-test1.sas
  Test/SAS/CodeGenerator/TestFiles/sas-test2.sas
  Test/SAS/CodeGenerator/TestFiles/sas-test3.sas
  Test/SAS/CodeGenerator/TestFiles/sas-test4.sas
  Test/SAS/CodeGenerator/TestFiles/sas-test5.sas
  Test/SAS/Parser/ParserTests.cpp
  Test/SAS/Rebuilder/RebuilderTests.cpp
  Test/SASCodeGenerator/CMakeLists.txt
  Test/SASCodeGenerator/SASCodeGenerator.cpp
  Test/SASCodeGenerator/example
  Test/SASParser/CMakeLists.txt
  src/CMakeLists.txt
  src/CommonInterface/CommonInterface.cpp
  src/CommonInterface/CommonInterface.hh
  src/Helpers/StringHelper.cpp
  src/Helpers/StringHelper.hh
  src/MacroGenerator/GroundedAction.hh
  src/PDDLCodeGenerator/PDDLDomainCodeGenerator.cpp
  src/Reformulators/BaseReformulator.cpp
  src/Reformulators/BaseReformulator.hh
  src/Reformulators/CMakeLists.txt
  src/Reformulators/SameOutputReformulator.cpp
  src/Reformulators/SameOutputReformulator.hh
  src/SAS/Action.hh
  src/SAS/CMakeLists.txt
  src/SAS/CodeGenerator/CodeGenerator.cpp
  src/SAS/CodeGenerator/CodeGenerator.hh
  src/SAS/Parser/Parser.cpp
  src/SAS/Parser/Parser.hh
  src/SAS/Plan.hh
  src/SAS/Rebuilder/Rebuilder.cpp
  src/SAS/Rebuilder/Rebuilder.hh
  src/SASCodeGenerator/CMakeLists.txt
  src/SASCodeGenerator/SASCodeGenerator.hh
  src/SASParser/CMakeLists.txt
  src/SASParser/SASParser.hh
  src/WalkerPathVerifyer/WalkerPathVerifyer.cpp
  src/WalkerPathVerifyer/WalkerPathVerifyer.hh
Labels: bug, test, refactor

#305 Added a new heuristic
  LabSettings/depot_walker_sameoutput.ini
  baseSettings.ini
  src/DownwardRunner/DownwardRunner.cpp
  src/IntermediatePDDL/PDDLActionInstance.hh
  src/Walker/Heuristics/BaseHeuristic.hh
  src/Walker/Heuristics/GoalCountHeuristic.hh
  src/Walker/Heuristics/GoalPredicateCountHeuristic.hh
  src/Walker/Heuristics/PreviousBaseHeuristic.hh
  src/Walker/Heuristics/RandomHeuristic.hh
  src/Walker/Variants/WalkerGreedy.cpp
  src/Walker/Variants/WalkerGreedyResume.cpp
  src/Walker/Variants/WalkerProbe.cpp
  src/Walker/Variants/WalkerQueue.cpp
  src/Walker/Variants/WalkerStepBack.cpp
  src/Walker/WalkerBuilder.cpp
  src/Walker/WalkerBuilder.hpp
Labels: bug, feature

#317 Fixed Lab with the regressor and updated the install script
  Lab/SettingsParser.py
  installScript.sh
Labels: bug

#320 Macro refactoring and tests
  CMakeLists.txt
  Test/CMakeLists.txt
  Test/MacroGenerator/CMakeLists.txt
  Test/MacroGenerator/MacroGenerator.cpp
  Test/Macros/CMakeLists.txt
  Test/Macros/Generators/GeneratorTests.cpp
  Test/Macros/Instantiators/InstantiatorTests.cpp
  Test/SAS/Rebuilder/RebuilderTests.cpp
  baseSettings.ini
  settings.ini
  settingsFast.ini
  src/CMakeLists.txt
  src/MacroGenerator/CMakeLists.txt
  src/MacroGenerator/GroundedAction.hh
  src/MacroGenerator/InstanceGenerator.cpp
  src/MacroGenerator/InstanceGenerator.hh
  src/MacroGenerator/Macro.hh
  src/MacroGenerator/MacroGenerator.cpp
  src/MacroGenerator/MacroGenerator.hh
  src/MacroVerifyer/CMakeLists.txt
  src/MacroVerifyer/MacroVerifyer.cpp
  src/MacroVerifyer/MacroVerifyer.hh
  src/Macros/CMakeLists.txt
  src/Macros/Generators/Generator.cpp
  src/Macros/Generators/Generator.hh
  src/Macros/GroundedAction.hh
  src/Macros/GroundedLiteral.hh
  src/Macros/Instantiators/Instantiator.cpp
  src/Macros/Instantiators/Instantiator.hh
  src/Macros/Macro.hh
  src/Reformulators/BaseReformulator.cpp
  src/Reformulators/BaseReformulator.hh
  src/Reformulators/CMakeLists.txt
  src/SAS/Rebuilder/Rebuilder.hh
Labels: test, refactor

#322 Additional lab info
  Lab/LabAttributes.py
  Lab/P7LabParser.py
  src/CommonInterface/CommonInterface.cpp
  src/Helpers/AlgorithmHelper.cpp
  src/Helpers/AlgorithmHelper.hh
  src/Reformulators/BaseReformulator.hh
  src/Reformulators/Walkers/GreedyResumeWalkerReformulator.cpp
  src/Reformulators/Walkers/GreedyWalkerReformulator.cpp
  src/Reformulators/Walkers/ProbeWalkerReformulator.cpp
  src/Reformulators/Walkers/QueueWalkerReformulator.cpp
  src/Reformulators/Walkers/StepBackWalkerReformulator.cpp
  src/Walker/ActionGenerator.cpp
  src/Walker/ActionGenerator.hpp
  src/Walker/ActionGenerator2.cpp
  src/Walker/ActionGenerator2.hpp
  src/Walker/BaseWalker.hh
  src/Walker/Variants/WalkerGreedy.cpp
  src/Walker/Variants/WalkerGreedyResume.cpp
  src/Walker/Variants/WalkerProbe.cpp
  src/Walker/Variants/WalkerQueue.cpp
  src/Walker/Variants/WalkerStepBack.cpp
Labels: feature

#323 Fixed the time split for direct mode
  baseSettings.ini
  settings.ini
  src/CommonInterface/CommonInterface.cpp
Labels: bug

#324 Fixed so that the timelimit is actually also the time limit
  baseSettings.ini
  settings.ini
  src/CommonInterface/CommonInterface.cpp
Labels: bug

#325 New graphs v2
  graphGeneration.R
  installScript.sh
Labels: feature

#326 Added unique macros used
  Lab/LabAttributes.py
  Lab/P7LabParser.py
  Test/SAS/Rebuilder/RebuilderTests.cpp
  src/CommonInterface/CommonInterface.cpp
  src/SAS/Action.hh
  src/SAS/Parser/Parser.cpp
  src/SAS/Plan.hh
  src/SAS/Rebuilder/Rebuilder.cpp
  src/WalkerPathVerifyer/WalkerPathVerifyer.cpp
Labels: feature

#327 Adds hill climber
  baseSettings.ini
  src/CommonInterface/CommonInterface.cpp
  src/CommonInterface/CommonInterface.hh
  src/Reformulators/CMakeLists.txt
  src/Reformulators/Walkers/HillClimberWalkerReformulator.cpp
  src/Reformulators/Walkers/HillClimberWalkerReformulator.hh
  src/Walker/CMakeLists.txt
  src/Walker/Variants/WalkerHillClimber.cpp
  src/Walker/Variants/WalkerHillClimber.hpp
  src/Walker/WalkerBuilder.cpp
  src/Walker/WalkerBuilder.hpp
Labels: feature

#328 Search time graphs
  LabSettings/depot_walker_sameoutput.ini
  graphGeneration.R
  installScript.sh
  src/Regressor/BaseRegressor.cpp
  src/Regressor/BaseRegressor.hh
  src/Regressor/PartialRegressor.cpp
  src/Regressor/PartialRegressor.hh
  src/Regressor/Regressor.cpp
  src/Regressor/Regressor.hh
Labels: feature
